version: "3.3"
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 127.0.0.5:80:80
    volumes:
      - .:/var/www
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/log:/var/log/nginx/
    working_dir: /var/www
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  php:
    build: ./docker/php
    volumes:
      - .:/var/www
    working_dir: /var/www

  redis:
    image: redis:latest
    container_name: redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 6379:6379

volumes:
  postgres-data: